add support for mac syntax for sed replace
Jett59/osmium-os pull request #15
Opened 2024-01-14 23:59 UTC by luketn

2024-01-15 03:01 UTC, Jett59 requested changes

2024-01-15 03:01 UTC, Jett59 commented on x86_64-config.sh
>  sed 's/"rust-analyzer.cargo.target": "aarch64-unknown-linux-gnu"/"rust-analyzer.cargo.target": "x86_64-unknown-linux-gnu"/g' -i kernel.code-workspace
Or this?

2024-01-18 00:42 UTC, luketn commented on aarch64-config.sh
>  sed 's/"rust-analyzer.cargo.target": "x86_64-unknown-linux-gnu"/"rust-analyzer.cargo.target": "aarch64-unknown-linux-gnu"/g' -i kernel.code-workspace
Good point!

2024-01-18 00:43 UTC, luketn commented on x86_64-config.sh
>  sed 's/"rust-analyzer.cargo.target": "aarch64-unknown-linux-gnu"/"rust-analyzer.cargo.target": "x86_64-unknown-linux-gnu"/g' -i kernel.code-workspace
done

2024-01-18 00:43 UTC, luketn commented on aarch64-config.sh
>  sed 's/"rust-analyzer.cargo.target": "x86_64-unknown-linux-gnu"/"rust-analyzer.cargo.target": "aarch64-unknown-linux-gnu"/g' -i kernel.code-workspace
done

2024-01-29 03:10 UTC, Jett59 approved these changes

2024-01-29 03:11 UTC, merged